// Code generated by mockery v2.46.1. DO NOT EDIT.

package mock_envoy

import mock "github.com/stretchr/testify/mock"

// CounterMetric is an autogenerated mock type for the CounterMetric type
type CounterMetric struct {
	mock.Mock
}

type CounterMetric_Expecter struct {
	mock *mock.Mock
}

func (_m *CounterMetric) EXPECT() *CounterMetric_Expecter {
	return &CounterMetric_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *CounterMetric) Get() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// CounterMetric_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CounterMetric_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *CounterMetric_Expecter) Get() *CounterMetric_Get_Call {
	return &CounterMetric_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *CounterMetric_Get_Call) Run(run func()) *CounterMetric_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CounterMetric_Get_Call) Return(_a0 uint64) *CounterMetric_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CounterMetric_Get_Call) RunAndReturn(run func() uint64) *CounterMetric_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: offset
func (_m *CounterMetric) Increment(offset int64) {
	_m.Called(offset)
}

// CounterMetric_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type CounterMetric_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - offset int64
func (_e *CounterMetric_Expecter) Increment(offset interface{}) *CounterMetric_Increment_Call {
	return &CounterMetric_Increment_Call{Call: _e.mock.On("Increment", offset)}
}

func (_c *CounterMetric_Increment_Call) Run(run func(offset int64)) *CounterMetric_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *CounterMetric_Increment_Call) Return() *CounterMetric_Increment_Call {
	_c.Call.Return()
	return _c
}

func (_c *CounterMetric_Increment_Call) RunAndReturn(run func(int64)) *CounterMetric_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: value
func (_m *CounterMetric) Record(value uint64) {
	_m.Called(value)
}

// CounterMetric_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type CounterMetric_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - value uint64
func (_e *CounterMetric_Expecter) Record(value interface{}) *CounterMetric_Record_Call {
	return &CounterMetric_Record_Call{Call: _e.mock.On("Record", value)}
}

func (_c *CounterMetric_Record_Call) Run(run func(value uint64)) *CounterMetric_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *CounterMetric_Record_Call) Return() *CounterMetric_Record_Call {
	_c.Call.Return()
	return _c
}

func (_c *CounterMetric_Record_Call) RunAndReturn(run func(uint64)) *CounterMetric_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewCounterMetric creates a new instance of CounterMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCounterMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *CounterMetric {
	mock := &CounterMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
