// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ResponseHeaderMap is an autogenerated mock type for the ResponseHeaderMap type
type ResponseHeaderMap struct {
	mock.Mock
}

// Add provides a mock function with given fields: key, value
func (_m *ResponseHeaderMap) Add(key string, value string) {
	_m.Called(key, value)
}

// ByteSize provides a mock function with given fields:
func (_m *ResponseHeaderMap) ByteSize() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// Del provides a mock function with given fields: key
func (_m *ResponseHeaderMap) Del(key string) {
	_m.Called(key)
}

// Get provides a mock function with given fields: key
func (_m *ResponseHeaderMap) Get(key string) (string, bool) {
	ret := _m.Called(key)

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetRaw provides a mock function with given fields: name
func (_m *ResponseHeaderMap) GetRaw(name string) string {
	ret := _m.Called(name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Range provides a mock function with given fields: f
func (_m *ResponseHeaderMap) Range(f func(string, string) bool) {
	_m.Called(f)
}

// RangeWithCopy provides a mock function with given fields: f
func (_m *ResponseHeaderMap) RangeWithCopy(f func(string, string) bool) {
	_m.Called(f)
}

// Set provides a mock function with given fields: key, value
func (_m *ResponseHeaderMap) Set(key string, value string) {
	_m.Called(key, value)
}

// Status provides a mock function with given fields:
func (_m *ResponseHeaderMap) Status() (int, bool) {
	ret := _m.Called()

	var r0 int
	var r1 bool
	if rf, ok := ret.Get(0).(func() (int, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Values provides a mock function with given fields: key
func (_m *ResponseHeaderMap) Values(key string) []string {
	ret := _m.Called(key)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewResponseHeaderMap creates a new instance of ResponseHeaderMap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponseHeaderMap(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResponseHeaderMap {
	mock := &ResponseHeaderMap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
